"""Generate complete, disjoint WOFF2 slices and a transfer/count manifest.
Install: python -m pip install -r scripts/font-requirements.txt
Run from any directory: python scripts/subset-fonts.py [--corpus article.txt]
"""
import argparse
from collections import Counter
from hashlib import sha256
from io import BytesIO
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'public/fonts/LXGWWenKai-Regular.9a343ba0.woff2'
OUTPUT = ROOT / 'public/fonts/lxgw-subsets'


def unicode_ranges(points):
    runs = []
    for point in sorted(points):
        if runs and point == runs[-1][1] + 1:
            runs[-1][1] = point
        else:
            runs.append([point, point])
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in runs)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, action='append', default=[])
    parser.add_argument('--chunk-size', type=int, default=256)
    args = parser.parse_args()
    if args.chunk_size < 1:
        parser.error('--chunk-size must be positive')
    # UI text is a reproducible initial corpus; exported articles can supplement it.
    files = sorted((ROOT / 'themes/fuwari').rglob('*.js'))
    files += sorted((ROOT / 'lib/lang').rglob('*.js'))
    files += args.corpus
    frequency = Counter(ord(c) for file in files for c in file.read_text(encoding='utf-8'))
    # Decode WOFF2 once; each subset reads the uncompressed SFNT in memory.
    with TTFont(SOURCE, recalcTimestamp=False) as font:
        original = set(font.getBestCmap())
        font.flavor = None
        sfnt = BytesIO()
        font.save(sfnt)
    source_data = sfnt.getvalue()
    print(f'Decoded {len(original)} characters', flush=True)
    basic = sorted(p for p in original if p < 0x100 or 0x2000 <= p <= 0x206F or 0x3000 <= p <= 0x303F or 0xFF00 <= p <= 0xFFEF)
    remaining = original - set(basic)
    common = sorted((p for p in remaining if frequency[p]), key=lambda p: (-frequency[p], p))
    rare = sorted(remaining - set(common))
    groups = [('base', basic)]
    for label, points in [('common', common), ('extended', rare)]:
        groups += [(f'{label}-{i // args.chunk_size:03}', points[i:i + args.chunk_size]) for i in range(0, len(points), args.chunk_size)]
    OUTPUT.mkdir(parents=True, exist_ok=True)
    entries, css, covered = [], [], set()
    for name, points in groups:
        if not points:
            continue
        font = TTFont(BytesIO(source_data), recalcTimestamp=False)
        options = subset.Options()
        options.recalc_timestamp = False
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=points)
        subsetter.subset(font)
        buffer = BytesIO()
        font.flavor = 'woff2'
        font.save(buffer)
        font.close()
        data = buffer.getvalue()
        # Validate the actual emitted binary, not just the planned ranges.
        with TTFont(BytesIO(data)) as emitted:
            actual = set(emitted.getBestCmap())
        assert actual == set(points), f'Glyph coverage changed: {name}'
        assert not covered & actual, f'Overlapping slice: {name}'
        covered.update(actual)
        filename = f'{name}.{sha256(data).hexdigest()[:12]}.woff2'
        (OUTPUT / filename).write_bytes(data)
        ranges = unicode_ranges(points)
        url = f'/fonts/lxgw-subsets/{filename}'
        print(f'{name}: {len(points)} characters, {len(data)} bytes', flush=True)
        entries.append(dict(name=name, url=url, characters=len(points), bytes=len(data), unicodeRange=ranges))
        css.append("@font-face {\n  font-family: 'LXGW WenKai';\n  font-style: normal;\n  font-weight: 400;\n  font-display: swap;\n" + f"  src: url('{url}') format('woff2');\n  unicode-range: {ranges};\n" + '}')
    assert covered == original, 'Source characters lost'
    manifest = dict(source=SOURCE.name, sourceBytes=SOURCE.stat().st_size, characters=len(original), chunkSize=args.chunk_size, packages=len(entries), totalBytes=sum(e['bytes'] for e in entries), subsets=entries)
    (OUTPUT / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
    (ROOT / 'styles/font-subsets.css').write_text('/* Generated by scripts/subset-fonts.py. Load only slices matching rendered text. */\n' + '\n\n'.join(css) + '\n')
    print(json.dumps({k: v for k, v in manifest.items() if k != 'subsets'}, indent=2))
    print(f"Slice size: {min(e['bytes'] for e in entries)}–{max(e['bytes'] for e in entries)} bytes")


if __name__ == '__main__':
    main()
